networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

services:
  api-gateway:
    build:
      context: ../sentiric-api-gateway-service
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: sentiric-api-gateway-service
    env_file:
      - ./.env
    volumes:
      - ../sentiric-infrastructure/tls/certs:/etc/sentiric/tls:ro
    ports:
      - "${API_GATEWAY_SERVICE_PORT}:${API_GATEWAY_SERVICE_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
    restart: always
    
  dashboard-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: sentiric-dashboard-ui
    env_file:
      - ./.env
    volumes:
      - ../sentiric-infrastructure/tls/certs:/etc/sentiric/tls:ro
    ports:
      - "${DASHBOARD_UI_PORT}:${DASHBOARD_UI_PORT}"
    networks:
      - sentiric-net
    profiles:
      - default
    restart: always

# Bu servisin diğerleriyle direkt konuşmasına gerek yok, sadece API Gateway'e istek atar.