# docker-compose.dev.yml
# Service Geliştirme ortamı

networks:
  sentiric-net:
    name: "${NETWORK_NAME:-sentiric-net}"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

# volumes:
  # [infra]: Temel Altyapı (Infrastructure Layer)
  # --------------------------------------------------

services:
  # [presentation-gateway]: Arayüz ve Giriş Katmanı (Presentation Layer)
  # --------------------------------------------------     

  dashboard-ui:
    image: ghcr.io/sentiric/sentiric-dashboard-ui:${TAG:-latest}
    env_file: ["${ENV_FILE_PATH}"]
    volumes: 
      - "${CONFIG_REPO_PATH}:/sentiric-config:ro"
      - "${CERTIFICATES_REPO_PATH}:/sentiric-certificates:ro"
      - "${ASSETS_REPO_PATH}:/sentiric-assets:ro"
    ports: 
      - "${DASHBOARD_UI_HTTP_PORT:-19010}:80"       
    networks:
      sentiric-net:
        ipv4_address: ${DASHBOARD_UI_IPV4_ADDRESS}
    dns:
      - ${PRIMARY_DNS:-8.8.8.8}
      - ${SECONDARY_DNS:-1.1.1.1} 
    restart: always
    # depends_on:
    #   api-gateway: { condition: service_healthy }  
